version: '3'

# This file uses all local resources.

services:

  redis:
    image: redis:alpine
    ports:
    - 6379:6379
    volumes:
    - ./redis-data:/data

  # loads data from OpenSky Network into Redis
  data-load:
    build:
      context: data-load
    environment:
    - REDIS_HOST=redis
    depends_on:
    - redis

  # includes both the Express api and Vue app
  webapp:
    build:
      context: .
    ports:
    - 8080:8080
    environment:
    - REDIS_HOST=redis
    depends_on:
    - redis
